### ISSUE TITLE
Use vim.fn.buflisted() to only handle important buffers

### ISSUE THREAD

**Issue by roman1267** [dseum/window.nvim#1]
Heyo, just came over from [reddit](https://www.reddit.com/r/neovim/comments/1amhd3h/comment/kplvxi5/?context=3).
I noticed in your readme.md that you mention that you have issues with oil.nvim. Have you thought about using `vim.fn.buflisted()` to clear unlisted buffers off your buffer stack? That way, plugins like oil or nvim-tree won't pollute the buffer list.

**Comment by dseum** [comment]
That's actually not the issue: the desired behavior is to be able to close unlisted buffers. What `oil.nvim` does is create a buffer for each directory because it needs to keep track of any changes that occur. This creates, for example, 7 buffers that I logically would like to close all at once. I've actually fixed it with the plugin's native timeout option, so I'll remove that from the README.

**Comment by roman1267** [comment]
I'll look into oil.nvim then to see if I can provide any further assistance. Thanks for the clarification!
